# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('DiagnosisId', models.AutoField(primary_key=True, serialize=False)),
                ('DiagnosisDescription', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('FacilityId', models.AutoField(primary_key=True, serialize=False)),
                ('FacilityName', models.CharField(max_length=4000)),
                ('FacilityType', models.CharField(max_length=200)),
                ('NumberOfPhysicians', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacilityAddress',
            fields=[
                ('FacilityAddressId', models.AutoField(primary_key=True, serialize=False)),
                ('StreetAddress1', models.CharField(max_length=100)),
                ('StreetAddress2', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
                ('Facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('InsuranceCompanyId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=4000)),
                ('StreetAddress1', models.CharField(max_length=100)),
                ('StreetAddress2', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=150)),
                ('MiddleName', models.CharField(max_length=150, null=True)),
                ('LastName', models.CharField(max_length=150)),
                ('UserName', models.CharField(max_length=150)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=2)),
                ('Race', models.CharField(max_length=10)),
                ('Ethnicity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('PatientAddressId', models.AutoField(primary_key=True, serialize=False)),
                ('StreetAddress1', models.CharField(max_length=100)),
                ('StreetAddress2', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('PatientInsuranceId', models.AutoField(primary_key=True, serialize=False)),
                ('PremiumType', models.CharField(max_length=10)),
                ('PremiumCost', models.DecimalField(decimal_places=2, max_digits=23)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('PatientMedicalHistoryId', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfVisit', models.DateField()),
                ('CostOfVisit', models.DecimalField(decimal_places=2, max_digits=23)),
                ('InsurancePercentage', models.DecimalField(decimal_places=10, max_digits=11)),
                ('Diagnosis', models.ManyToManyField(to='api.Diagnosis')),
                ('Facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.Facility')),
                ('InsuranceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.InsuranceCompany')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientOccupation',
            fields=[
                ('PatientOccupationId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyLocation', models.CharField(max_length=100)),
                ('PositionTitle', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=23)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='api.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('SymptomId', models.AutoField(primary_key=True, serialize=False)),
                ('Symptom', models.CharField(max_length=100)),
                ('SymptomDescription', models.CharField(max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='Symptom',
            field=models.ManyToManyField(to='api.Symptom'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='Symptom',
            field=models.ManyToManyField(to='api.Symptom'),
        ),
    ]
