# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityaddress',
            name='StreetAddress2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='StreetAddress2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='StreetAddress2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
